spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/freshcup?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true

server:
  port: 8080

logging:
  level:
    sast.freshcup.mapper: debug